begin;
create temporary table fixture (key text primary key, id uuid not null default gen_random_uuid());
insert into fixture(key) values ('ua'),('ub'),('staff'),('viewer'),('suspended'),('outsider'),('dual'),('oa'),('ob'),('ma'),('mb'),('orga'),('orgb'),('ca'),('cb'),('casea'),('caseb');
grant select on fixture to anon,authenticated;
create function pg_temp.f(k text) returns uuid language sql stable as $$ select id from pg_temp.fixture where key=k $$;
create temporary table test_results(label text, passed boolean, actual_state text, actual_rows bigint);
grant insert,select on test_results to anon,authenticated;
create function pg_temp.verify(label text, statement text, expected_rows bigint, expected_state text default null) returns void
language plpgsql security invoker as $$
declare n bigint; st text;
begin
 begin execute statement; get diagnostics n=row_count;
 exception when others then st:=SQLSTATE; end;
 insert into pg_temp.test_results values (label,
 case when expected_state is not null then st=expected_state else st is null and n=expected_rows end,
 st,n);
end $$;
insert into auth.users(id,aud,role) select id,'authenticated','authenticated' from fixture where key in ('ua','ub','staff','viewer','suspended','outsider','dual');
insert into public.offices(id,name) values (pg_temp.f('oa'),'Phase1 test A'),(pg_temp.f('ob'),'Phase1 test B');
insert into public.office_members(id,office_id,user_id,role) values
(pg_temp.f('ma'),pg_temp.f('oa'),pg_temp.f('ua'),'owner'),
(pg_temp.f('mb'),pg_temp.f('ob'),pg_temp.f('ub'),'owner');
insert into public.office_members(office_id,user_id,role,status) values
(pg_temp.f('oa'),pg_temp.f('staff'),'staff','active'),
(pg_temp.f('oa'),pg_temp.f('viewer'),'viewer','active'),
(pg_temp.f('oa'),pg_temp.f('suspended'),'staff','suspended'),
(pg_temp.f('oa'),pg_temp.f('dual'),'admin','active'),
(pg_temp.f('ob'),pg_temp.f('dual'),'admin','active');
insert into public.organizations(id,office_id,name) values (pg_temp.f('orga'),pg_temp.f('oa'),'Org A'),(pg_temp.f('orgb'),pg_temp.f('ob'),'Org B');
insert into public.contacts(id,office_id,display_name,organization_id) values
(pg_temp.f('ca'),pg_temp.f('oa'),'Contact A',pg_temp.f('orga')),
(pg_temp.f('cb'),pg_temp.f('ob'),'Contact B',pg_temp.f('orgb'));
insert into public.office_cases(id,office_id,case_number,title,primary_contact_id,organization_id,assigned_member_id) values
(pg_temp.f('casea'),pg_temp.f('oa'),'TEST-1','Case A',pg_temp.f('ca'),pg_temp.f('orga'),pg_temp.f('ma')),
(pg_temp.f('caseb'),pg_temp.f('ob'),'TEST-1','Case B',pg_temp.f('cb'),pg_temp.f('orgb'),pg_temp.f('mb'));
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select pg_temp.verify('anon offices select denied','select * from public.offices',null,'42501');
select pg_temp.verify('anon offices insert denied','insert into public.offices(name) values (''forbidden'')',null,'42501');
select pg_temp.verify('anon offices update denied','update public.offices set name=name',null,'42501');
select pg_temp.verify('anon offices delete denied','delete from public.offices',null,'42501');
select pg_temp.verify('anon office_members select denied','select * from public.office_members',null,'42501');
select pg_temp.verify('anon office_members insert denied','insert into public.office_members(office_id,user_id) values (pg_temp.f(''oa''),pg_temp.f(''outsider''))',null,'42501');
select pg_temp.verify('anon office_members update denied','update public.office_members set role=role',null,'42501');
select pg_temp.verify('anon office_members delete denied','delete from public.office_members',null,'42501');
select pg_temp.verify('anon contacts select denied','select * from public.contacts',null,'42501');
select pg_temp.verify('anon contacts insert denied','insert into public.contacts(office_id,display_name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('anon contacts update denied','update public.contacts set display_name=display_name',null,'42501');
select pg_temp.verify('anon contacts delete denied','delete from public.contacts',null,'42501');
select pg_temp.verify('anon organizations select denied','select * from public.organizations',null,'42501');
select pg_temp.verify('anon organizations insert denied','insert into public.organizations(office_id,name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('anon organizations update denied','update public.organizations set name=name',null,'42501');
select pg_temp.verify('anon organizations delete denied','delete from public.organizations',null,'42501');
select pg_temp.verify('anon office_cases select denied','select * from public.office_cases',null,'42501');
select pg_temp.verify('anon office_cases insert denied','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-new'',''new'')',null,'42501');
select pg_temp.verify('anon office_cases update denied','update public.office_cases set title=title',null,'42501');
select pg_temp.verify('anon office_cases delete denied','delete from public.office_cases',null,'42501');
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('outsider')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('outsider offices select hidden','select * from public.offices',0);
select pg_temp.verify('outsider offices insert denied','insert into public.offices(name) values (''forbidden'')',null,'42501');
select pg_temp.verify('outsider offices update denied','update public.offices set name=name',0);
select pg_temp.verify('outsider offices delete denied','delete from public.offices',null,'42501');
select pg_temp.verify('outsider office_members select hidden','select * from public.office_members',0);
select pg_temp.verify('outsider office_members insert denied','insert into public.office_members(office_id,user_id) values (pg_temp.f(''oa''),pg_temp.f(''outsider''))',null,'42501');
select pg_temp.verify('outsider office_members update denied','update public.office_members set role=role',null,'42501');
select pg_temp.verify('outsider office_members delete denied','delete from public.office_members',null,'42501');
select pg_temp.verify('outsider contacts select hidden','select * from public.contacts',0);
select pg_temp.verify('outsider contacts insert denied','insert into public.contacts(office_id,display_name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('outsider contacts update denied','update public.contacts set display_name=display_name',0);
select pg_temp.verify('outsider contacts delete denied','delete from public.contacts',0);
select pg_temp.verify('outsider organizations select hidden','select * from public.organizations',0);
select pg_temp.verify('outsider organizations insert denied','insert into public.organizations(office_id,name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('outsider organizations update denied','update public.organizations set name=name',0);
select pg_temp.verify('outsider organizations delete denied','delete from public.organizations',0);
select pg_temp.verify('outsider office_cases select hidden','select * from public.office_cases',0);
select pg_temp.verify('outsider office_cases insert denied','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-new'',''new'')',null,'42501');
select pg_temp.verify('outsider office_cases update denied','update public.office_cases set title=title',0);
select pg_temp.verify('outsider office_cases delete denied','delete from public.office_cases',0);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('suspended')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('suspended offices select hidden','select * from public.offices',0);
select pg_temp.verify('suspended offices insert denied','insert into public.offices(name) values (''forbidden'')',null,'42501');
select pg_temp.verify('suspended offices update denied','update public.offices set name=name',0);
select pg_temp.verify('suspended offices delete denied','delete from public.offices',null,'42501');
select pg_temp.verify('suspended office_members select hidden','select * from public.office_members',0);
select pg_temp.verify('suspended office_members insert denied','insert into public.office_members(office_id,user_id) values (pg_temp.f(''oa''),pg_temp.f(''outsider''))',null,'42501');
select pg_temp.verify('suspended office_members update denied','update public.office_members set role=role',null,'42501');
select pg_temp.verify('suspended office_members delete denied','delete from public.office_members',null,'42501');
select pg_temp.verify('suspended contacts select hidden','select * from public.contacts',0);
select pg_temp.verify('suspended contacts insert denied','insert into public.contacts(office_id,display_name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('suspended contacts update denied','update public.contacts set display_name=display_name',0);
select pg_temp.verify('suspended contacts delete denied','delete from public.contacts',0);
select pg_temp.verify('suspended organizations select hidden','select * from public.organizations',0);
select pg_temp.verify('suspended organizations insert denied','insert into public.organizations(office_id,name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('suspended organizations update denied','update public.organizations set name=name',0);
select pg_temp.verify('suspended organizations delete denied','delete from public.organizations',0);
select pg_temp.verify('suspended office_cases select hidden','select * from public.office_cases',0);
select pg_temp.verify('suspended office_cases insert denied','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-new'',''new'')',null,'42501');
select pg_temp.verify('suspended office_cases update denied','update public.office_cases set title=title',0);
select pg_temp.verify('suspended office_cases delete denied','delete from public.office_cases',0);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('ua')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('owner A offices own read','select * from public.offices',1);
select pg_temp.verify('owner A offices cross read','select * from public.offices where id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A offices cross insert','insert into public.offices(name) values (''forbidden'')',null,'42501');
select pg_temp.verify('owner A offices cross update','update public.offices set name=name where id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A offices cross delete','delete from public.offices where id=pg_temp.f(''ob'')',null,'42501');
select pg_temp.verify('owner A office_members own read','select * from public.office_members',1);
select pg_temp.verify('owner A office_members cross read','select * from public.office_members where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A office_members cross insert','insert into public.office_members(office_id,user_id) values (pg_temp.f(''ob''),pg_temp.f(''outsider''))',null,'42501');
select pg_temp.verify('owner A office_members cross update','update public.office_members set role=role where office_id=pg_temp.f(''ob'')',null,'42501');
select pg_temp.verify('owner A office_members cross delete','delete from public.office_members where office_id=pg_temp.f(''ob'')',null,'42501');
select pg_temp.verify('owner A contacts own read','select * from public.contacts',1);
select pg_temp.verify('owner A contacts cross read','select * from public.contacts where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A contacts cross insert','insert into public.contacts(office_id,display_name) values (pg_temp.f(''ob''),''new'')',null,'42501');
select pg_temp.verify('owner A contacts cross update','update public.contacts set display_name=display_name where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A contacts cross delete','delete from public.contacts where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A organizations own read','select * from public.organizations',1);
select pg_temp.verify('owner A organizations cross read','select * from public.organizations where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A organizations cross insert','insert into public.organizations(office_id,name) values (pg_temp.f(''ob''),''new'')',null,'42501');
select pg_temp.verify('owner A organizations cross update','update public.organizations set name=name where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A organizations cross delete','delete from public.organizations where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A office_cases own read','select * from public.office_cases',1);
select pg_temp.verify('owner A office_cases cross read','select * from public.office_cases where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A office_cases cross insert','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''ob''),''TEST-new'',''new'')',null,'42501');
select pg_temp.verify('owner A office_cases cross update','update public.office_cases set title=title where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner A office_cases cross delete','delete from public.office_cases where office_id=pg_temp.f(''ob'')',0);
select pg_temp.verify('owner cannot self-promote membership','update public.office_members set role=''admin''',null,'42501');
select pg_temp.verify('owner own offices update','update public.offices set name=name',1);
select pg_temp.verify('owner own contacts update','update public.contacts set display_name=display_name',1);
select pg_temp.verify('owner own organizations update','update public.organizations set name=name',1);
select pg_temp.verify('owner own office_cases update','update public.office_cases set title=title',1);
select pg_temp.verify('owner own contacts create','insert into public.contacts(office_id,display_name) values (pg_temp.f(''oa''),''new'')',1);
select pg_temp.verify('owner own contacts delete','delete from public.contacts where display_name=''new''',1);
select pg_temp.verify('owner own organizations create','insert into public.organizations(office_id,name) values (pg_temp.f(''oa''),''new'')',1);
select pg_temp.verify('owner own organizations delete','delete from public.organizations where name=''new''',1);
select pg_temp.verify('owner own office_cases create','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-new'',''new'')',1);
select pg_temp.verify('owner own office_cases delete','delete from public.office_cases where title=''new''',1);
select pg_temp.verify('case cross tenant FK primary_contact_id','update public.office_cases set primary_contact_id=pg_temp.f(''cb'') where id=pg_temp.f(''casea'')',null,'23503');
select pg_temp.verify('case cross tenant FK organization_id','update public.office_cases set organization_id=pg_temp.f(''orgb'') where id=pg_temp.f(''casea'')',null,'23503');
select pg_temp.verify('case cross tenant FK assigned_member_id','update public.office_cases set assigned_member_id=pg_temp.f(''mb'') where id=pg_temp.f(''casea'')',null,'23503');
select pg_temp.verify('contact cross tenant organization FK','update public.contacts set organization_id=pg_temp.f(''orgb'') where id=pg_temp.f(''ca'')',null,'23503');
select pg_temp.verify('sensitive ciphertext remains disabled','update public.contacts set national_id_encrypted=decode(''abcd'',''hex'') where id=pg_temp.f(''ca'')',null,'23514');
select pg_temp.verify('sensitive hash remains disabled','update public.contacts set national_id_hash=decode(''abcd'',''hex'') where id=pg_temp.f(''ca'')',null,'23514');
select pg_temp.verify('case number unique per tenant','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-1'',''duplicate'')',null,'23505');
select pg_temp.verify('case invalid status rejected','update public.office_cases set status=''bogus''',null,'23514');
select pg_temp.verify('case invalid dates rejected','update public.office_cases set opened_on=''2026-09-16'',closed_on=''2026-09-15''',null,'23514');
select pg_temp.verify('empty name rejected','update public.contacts set display_name='' ''',null,'23514');
select pg_temp.verify('identity immutable','update public.contacts set id=gen_random_uuid()',null,'23514');
select pg_temp.verify('created_at immutable','update public.contacts set created_at=''2000-01-01''',null,'23514');
select pg_temp.verify('updated_at cannot be forged','update public.contacts set updated_at=''2000-01-01''',1);
select pg_temp.verify('updated_at generated by database','select * from public.contacts where updated_at <> ''2000-01-01'' and updated_at>=created_at',1);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('dual')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('dual member office_members tenant immutable','update public.office_members set office_id=pg_temp.f(''ob'') where office_id=pg_temp.f(''oa'')',null,'42501');
select pg_temp.verify('dual member contacts tenant immutable','update public.contacts set office_id=pg_temp.f(''ob'') where office_id=pg_temp.f(''oa'')',null,'23514');
select pg_temp.verify('dual member organizations tenant immutable','update public.organizations set office_id=pg_temp.f(''ob'') where office_id=pg_temp.f(''oa'')',null,'23514');
select pg_temp.verify('dual member office_cases tenant immutable','update public.office_cases set office_id=pg_temp.f(''ob'') where office_id=pg_temp.f(''oa'')',null,'23514');
select pg_temp.verify('dual member sees both offices','select * from public.offices',2);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('staff')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('staff contacts read','select * from public.contacts',1);
select pg_temp.verify('staff contacts update','update public.contacts set display_name=display_name',1);
select pg_temp.verify('staff contacts delete denied','delete from public.contacts',0);
select pg_temp.verify('staff contacts create','insert into public.contacts(office_id,display_name) values (pg_temp.f(''oa''),''new'')',1);
select pg_temp.verify('staff organizations read','select * from public.organizations',1);
select pg_temp.verify('staff organizations update','update public.organizations set name=name',1);
select pg_temp.verify('staff organizations delete denied','delete from public.organizations',0);
select pg_temp.verify('staff organizations create','insert into public.organizations(office_id,name) values (pg_temp.f(''oa''),''new'')',1);
select pg_temp.verify('staff office_cases read','select * from public.office_cases',1);
select pg_temp.verify('staff office_cases update','update public.office_cases set title=title',1);
select pg_temp.verify('staff office_cases delete denied','delete from public.office_cases',0);
select pg_temp.verify('staff office_cases create','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-new'',''new'')',1);
select pg_temp.verify('staff office edit denied','update public.offices set name=name',0);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('viewer')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('viewer contacts read','select * from public.contacts',2);
select pg_temp.verify('viewer contacts insert denied','insert into public.contacts(office_id,display_name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('viewer contacts update denied','update public.contacts set display_name=display_name',0);
select pg_temp.verify('viewer contacts delete denied','delete from public.contacts',0);
select pg_temp.verify('viewer organizations read','select * from public.organizations',2);
select pg_temp.verify('viewer organizations insert denied','insert into public.organizations(office_id,name) values (pg_temp.f(''oa''),''new'')',null,'42501');
select pg_temp.verify('viewer organizations update denied','update public.organizations set name=name',0);
select pg_temp.verify('viewer organizations delete denied','delete from public.organizations',0);
select pg_temp.verify('viewer office_cases read','select * from public.office_cases',2);
select pg_temp.verify('viewer office_cases insert denied','insert into public.office_cases(office_id,case_number,title) values (pg_temp.f(''oa''),''TEST-new'',''new'')',null,'42501');
select pg_temp.verify('viewer office_cases update denied','update public.office_cases set title=title',0);
select pg_temp.verify('viewer office_cases delete denied','delete from public.office_cases',0);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('ua')::text,'role','authenticated','is_anonymous',true)::text,true);
set local role authenticated;
select pg_temp.verify('anonymous Auth user offices denied','select * from public.offices',0);
select pg_temp.verify('anonymous Auth user office_members denied','select * from public.office_members',0);
select pg_temp.verify('anonymous Auth user contacts denied','select * from public.contacts',0);
select pg_temp.verify('anonymous Auth user organizations denied','select * from public.organizations',0);
select pg_temp.verify('anonymous Auth user office_cases denied','select * from public.office_cases',0);
reset role;
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('ub')::text,'role','authenticated','is_anonymous',false)::text,true);
set local role authenticated;
select pg_temp.verify('owner B offices only own rows','select * from public.offices',1);
select pg_temp.verify('owner B office_members only own rows','select * from public.office_members',1);
select pg_temp.verify('owner B contacts only own rows','select * from public.contacts',1);
select pg_temp.verify('owner B organizations only own rows','select * from public.organizations',1);
select pg_temp.verify('owner B office_cases only own rows','select * from public.office_cases',1);
reset role;
select jsonb_build_object('tests',count(*),'passed',count(*) filter(where passed is true),'failures',coalesce(jsonb_agg(to_jsonb(r)) filter(where passed is not true),'[]'::jsonb),'results',jsonb_agg(to_jsonb(r))) as verification from test_results r;
rollback;
