begin;
create temporary table f(key text primary key,id uuid default gen_random_uuid());
insert into f(key) values('a'),('b'),('staff'),('viewer'),('outsider'),('suspended'),('oa'),('ob'),('ca'),('cb'),('request'),('newrequest');
grant select on f to authenticated,anon;
create function pg_temp.uid(k text) returns uuid language sql as $$select id from pg_temp.f where key=k$$;
create temporary table fixture(payload jsonb);
insert into fixture values('{"version":1,"pageCount":1,"properties":[{"kind":"土地","fields":[{"key":"district","value":"測試區","page":1,"reviewed":true},{"key":"section","value":"測試段","page":1,"reviewed":true},{"key":"number","value":"0001-0000","page":1,"reviewed":true},{"key":"area","value":"100.00","page":1,"reviewed":true}],"owners":[{"fields":[{"key":"name","value":"測**","page":1,"reviewed":true}]}],"common":[],"rights":[]}]}');
grant select on fixture to authenticated,anon;
create function pg_temp.payload() returns jsonb language sql as $$select payload from pg_temp.fixture$$;
create temporary table results(label text,passed boolean,actual text);
grant insert,select on results to authenticated,anon;
create function pg_temp.verify(label text,q text,expected text) returns void language plpgsql security invoker as $$
declare actual text;
begin begin execute q into actual; exception when others then actual:=SQLSTATE; end;
insert into pg_temp.results values(label,actual is not distinct from expected,actual);end$$;
insert into auth.users(id,aud,role,email,email_confirmed_at,is_anonymous)
 select id,'authenticated','authenticated',id::text||'@example.invalid',now(),false from f where key in('a','b','staff','viewer','outsider','suspended');
insert into public.offices(id,name) values(pg_temp.uid('oa'),'TRANSCRIPT TEST A'),(pg_temp.uid('ob'),'TRANSCRIPT TEST B');
insert into public.office_members(office_id,user_id,role,status) values
 (pg_temp.uid('oa'),pg_temp.uid('a'),'owner','active'),(pg_temp.uid('ob'),pg_temp.uid('b'),'owner','active'),
 (pg_temp.uid('oa'),pg_temp.uid('staff'),'staff','active'),(pg_temp.uid('oa'),pg_temp.uid('viewer'),'viewer','active'),(pg_temp.uid('oa'),pg_temp.uid('suspended'),'staff','suspended');
insert into public.office_cases(id,office_id,case_number,title) values(pg_temp.uid('ca'),pg_temp.uid('oa'),'TEST-A','Test A'),(pg_temp.uid('cb'),pg_temp.uid('ob'),'TEST-B','Test B');
set local role anon;
select pg_temp.verify('anon read denied',$q$select count(*)::text from public.office_case_transcripts$q$,'42501');
select pg_temp.verify('anon rpc denied',$q$select public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('request'),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{}',true);
select pg_temp.verify('missing user denied',$q$select public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('request'),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('a'),'role','authenticated')::text,true);
select pg_temp.verify('valid payload',$q$select public.office_valid_transcript(pg_temp.payload())::text$q$,'true');
select pg_temp.verify('missing version rejected',$q$select public.office_valid_transcript(pg_temp.payload()-'version')::text$q$,'false');
select pg_temp.verify('unknown fields rejected',$q$select public.office_valid_transcript(pg_temp.payload()||'{"national_id":"secret"}'::jsonb)::text$q$,'false');
select pg_temp.verify('identity hidden in name rejected',$q$select public.office_valid_transcript(jsonb_set(pg_temp.payload(),'{properties,0,owners,0,fields,0,value}','"A123456789"'))::text$q$,'false');
select pg_temp.verify('unchecked rejected',$q$select public.office_valid_transcript(jsonb_set(pg_temp.payload(),'{properties,0,fields,0,reviewed}','false'))::text$q$,'false');
select pg_temp.verify('invalid source page rejected',$q$select public.office_valid_transcript(jsonb_set(pg_temp.payload(),'{properties,0,fields,0,page}','2'))::text$q$,'false');
select pg_temp.verify('wrong tenant case rejected',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('cb'))::text$q$,'42501');
select pg_temp.verify('own case saves',$q$select (public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('request'),pg_temp.payload(),pg_temp.uid('ca'))->>'case_id')$q$,pg_temp.uid('ca')::text);
select pg_temp.verify('author server controlled',$q$select (created_by=auth.uid())::text from public.office_case_transcripts where id=pg_temp.uid('request')$q$,'true');
select pg_temp.verify('retry same request idempotent',$q$select public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('request'),pg_temp.payload(),pg_temp.uid('ca'))->>'duplicate'$q$,'true');
select pg_temp.verify('same content deduplicated',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('ca'))->>'duplicate'$q$,'true');
select pg_temp.verify('only one record',$q$select count(*)::text from public.office_case_transcripts where case_id=pg_temp.uid('ca')$q$,'1');
select pg_temp.verify('request cannot change case',$q$select public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('request'),pg_temp.payload(),pg_temp.uid('cb'))::text$q$,'22023');
select pg_temp.verify('direct tenant FK cannot cross',$q$insert into public.office_case_transcripts(office_id,case_id,payload) values(pg_temp.uid('oa'),pg_temp.uid('cb'),pg_temp.payload()) returning id::text$q$,'23503');
select pg_temp.verify('direct payload cannot bypass validation',$q$insert into public.office_case_transcripts(office_id,case_id,payload) values(pg_temp.uid('oa'),pg_temp.uid('ca'),'{}') returning id::text$q$,'23514');
select pg_temp.verify('direct author spoof denied',$q$insert into public.office_case_transcripts(office_id,case_id,payload,created_by) values(pg_temp.uid('oa'),pg_temp.uid('ca'),pg_temp.payload(),pg_temp.uid('b')) returning id::text$q$,'42501');
select pg_temp.verify('immutable update denied',$q$update public.office_case_transcripts set payload=pg_temp.payload() returning id::text$q$,'42501');
select pg_temp.verify('immutable delete denied',$q$delete from public.office_case_transcripts returning id::text$q$,'42501');
select pg_temp.verify('create case and import atomically',$q$select (public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('newrequest'),pg_temp.payload(),null,'NEW-TEST','New test')->>'case_id' is not null)::text$q$,'true');
select pg_temp.verify('new case retry idempotent',$q$select public.office_save_transcript(pg_temp.uid('oa'),pg_temp.uid('newrequest'),pg_temp.payload(),null,'NEW-TEST','New test')->>'duplicate'$q$,'true');
select pg_temp.verify('new case only once',$q$select count(*)::text from public.office_cases where office_id=pg_temp.uid('oa') and case_number='NEW-TEST'$q$,'1');
select pg_temp.verify('invalid new case payload aborts',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),'{}',null,'INVALID-TEST','Should not exist')::text$q$,'22023');
select pg_temp.verify('failed import leaves no case',$q$select count(*)::text from public.office_cases where case_number='INVALID-TEST'$q$,'0');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('b'),'role','authenticated')::text,true);
select pg_temp.verify('cross office reads zero',$q$select count(*)::text from public.office_case_transcripts where office_id=pg_temp.uid('oa')$q$,'0');
select pg_temp.verify('cross office rpc denied',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('outsider'),'role','authenticated')::text,true);
select pg_temp.verify('non member reads zero',$q$select count(*)::text from public.office_case_transcripts$q$,'0');
select pg_temp.verify('non member rpc denied',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('viewer'),'role','authenticated')::text,true);
select pg_temp.verify('viewer can read',$q$select count(*)::text from public.office_case_transcripts where case_id=pg_temp.uid('ca')$q$,'1');
select pg_temp.verify('viewer cannot write',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('suspended'),'role','authenticated')::text,true);
select pg_temp.verify('suspended reads zero',$q$select count(*)::text from public.office_case_transcripts$q$,'0');
select pg_temp.verify('suspended write denied',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('a'),'role','authenticated','is_anonymous',true)::text,true);
select pg_temp.verify('anonymous auth write denied',$q$select public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),pg_temp.payload(),pg_temp.uid('ca'))::text$q$,'42501');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.uid('staff'),'role','authenticated')::text,true);
select pg_temp.verify('staff can save new content',$q$select (public.office_save_transcript(pg_temp.uid('oa'),gen_random_uuid(),jsonb_set(pg_temp.payload(),'{properties,0,fields,3,value}','"101.00"'),pg_temp.uid('ca'))->>'record_id' is not null)::text$q$,'true');
reset role;
select jsonb_build_object('total',count(*),'passed',count(*) filter(where passed),'failures',coalesce(jsonb_agg(to_jsonb(r)) filter(where not passed),'[]'::jsonb)) as tests from results r;
rollback;
